# Generated by Django 4.2.5 on 2023-10-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_articletag_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='scopes', to='articles.tag'),
        ),
    ]
