# Generated by Django 4.2.5 on 2023-10-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(related_name='articles', to='articles.article'),
        ),
        migrations.AddField(
            model_name='scope',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='articles.tag'),
        ),
    ]
