# Generated by Django 4.2.5 on 2023-10-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_tags_alter_scope_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.tag'),
        ),
    ]
