# Generated by Django 4.2.5 on 2023-10-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='tags',
        ),
    ]
