# Generated by Django 4.2.5 on 2023-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_rename_scopes_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scope', through='articles.Scope', to='articles.tag'),
        ),
    ]
